modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Entropy159/Supernotes/issues"
license="CC BY-NC-SA 4.0"
[[mods]]
    modId="supernotes"
    version="${mod_version}"
    displayName="Supernotes"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/notes"
    authors="ChaosTheDude, Entropy159"
    description='''
    Clientside in-game notepad.
    '''

[[dependencies.supernotes]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.supernotes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
